language = "Typescript"
source_dir = "olap"

[state_config]
storage = "clickhouse"

[clickhouse_config]
db_name = "local"
user = "panda"
password = "pandapass"
use_ssl = false
host = "localhost"
host_port = 18123
native_port = 9000

[http_server_config]
host = "localhost"
port = 4000
management_port = 5001
# Script to run when files in source_dir change
# This will recompile OLAP models when olap/index.ts changes
on_reload_complete_script = "tsc -p tsconfig.olap.json"

[features]
streaming_engine = false
data_model_v2 = true

